root = "."
tmp_dir = "tmp"
[build]
  # compile into your tmp directory
  cmd = "go build -o bin/user-service cmd/main.go"
  # point Air at the binary it needs to execute
  bin = "bin/user-service"
  include_ext = ["go", "graphqls", "tmpl", "html", "env"]

[log]
  level = "debug"